

name: CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#
  #workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Check_Code_Style:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install python3-pip -y
          pip install flake8
      - name: Check code style
        run: python -m flake8 ./ --ignore=F401,E402
        
    
  Tests:
    runs-on: self-hosted
    needs: Check_Code_Style
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          pip install -e '.[test]'
          python -m coverage run -m pytest
          python -m coverage report
          
          
  Docker_Build_and_Deploy:
    runs-on: self-hosted
    needs: Tests
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker build
        run: sudo docker build . --tag lab3
      - 
        name: Change tag
        run: sudo docker image tag lab3 itatsenko/lab3:$GITHUB_RUN_ID
      - 
        name: Push docker
        run: sudo docker push itatsenko/lab3:$GITHUB_RUN_ID
      -
        name: Docker run
        run: |
          sudo docker ps
          sudo docker rm -f lab3
          sudo docker run -d -p 8080:5000 --name lab3 itatsenko/lab3:$GITHUB_RUN_ID
