

name: CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#
  #workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Check_Code_Style:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install flake8
      - name: Check code style
        run: python3 -m flake8 ./ --ignore=F401,E402
        
    
  Tests:
    runs-on: self-hosted
    needs: Check_Code_Style
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage report
          
  
          
  Docker_Build_and_Deploy:
    runs-on: self-hosted
    needs: Tests
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lab3 -f Dockerfile .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab3
      - name: Run
        run: |
          docker ps
          docker rm -f lab3
          docker run -d -p 8080:5000 --name lab3 itatsenko/lab3
