# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Check_Code_Style:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:  pip install flake8
      - name: Check code style
        run: python -m flake8 ./ --ignore=F401,E402
        
    
  Tests:
    runs-on: ubuntu-latest
    needs: Check_Code_Style
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          pip install -e '.[test]'
          python -m coverage run -m pytest
          python -m coverage report
          
          
  Docker_Build_and_Deploy:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build
        run: sudo docker build . --tag test
      - 
        name: Tag Change
        run: sudo docker image tag test 28122001/test:$GITHUB_RUN_ID
      - 
        name: Push Docker on DockertHub
        run: sudo docker push 28122001/test:$GITHUB_RUN_ID
      -
        name: Run
        run: |
          sudo docker ps
          sudo docker rm -f test
          sudo docker run -d -p 8080:5000 --name test 28122001/test:$GITHUB_RUN_ID
